services:
  better_reads:
    build: .
    stdin_open: true
    tty: true
    image: better_reads:latest
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
  tailwind:
    image: better_reads:latest
    tty: true
    command: "tailwind-compose"
    volumes:
      - .:/rails