services:
  better_reads:
    build: .
    image: better_reads:latest
    volumes:
      - .:/rails
      - gem_cache:/usr/local/bundle
    ports:
      - "3000:3000"
  tailwind:
    image: better_reads:latest
    tty: true
    command: "tailwind-compose"
    volumes:
      - .:/rails
      - gem_cache:/usr/local/bundle

volumes:
  gem_cache: